exports.storesMocks = function() {
    return [
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f0851",
            name:"La Farola",
            business_name:"La Farola S.A.",
            address:{
                name:"Av. Paseo Colón 850",
                lat:-34.617591,
                lon:-58.368398
            },
            availability:{
                monday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                sunday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f1829",
            name:"La Birra Night",
            business_name:"La Birra",
            address:{
                name:"Av. Independencia 4317",
                lat:-34.617591,
                lon:-58.368561
            },
            availability:{
                monday:{
                    "start_time":"20:00:00",
                    "end_time":"23:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Burger Kid",
                    "price":280
                }
            ],
            delay_time:{
                min:40,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f0832",
            name:"San Carlos",
            business_name:"Pizzería San Carlos SRL",
            address:{
                name:"Av. Rivadavia 4480",
                lat:-34.617507,
                lon:-58.368538
            },
            availability:{
                monday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                tuesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                wednesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                thursday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                friday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                saturday:{
                    "start_time":"00:00:00",
                    "end_time":"00:00:00"
                },
                sunday:{
                    "start_time":"09:00:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },{
            id:"d290f1ee-6c54-4b01-90e6-d701748f0851",
            name:"La Farola",
            business_name:"La Farola S.A.",
            address:{
                name:"Av. Paseo Colón 850",
                lat:-34.617591,
                lon:-58.368398
            },
            availability:{
                monday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                sunday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f1829",
            name:"La Birra Night",
            business_name:"La Birra",
            address:{
                name:"Av. Independencia 4317",
                lat:-34.617591,
                lon:-58.368561
            },
            availability:{
                monday:{
                    "start_time":"20:00:00",
                    "end_time":"23:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Burger Kid",
                    "price":280
                }
            ],
            delay_time:{
                min:40,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f0832",
            name:"San Carlos",
            business_name:"Pizzería San Carlos SRL",
            address:{
                name:"Av. Rivadavia 4480",
                lat:-34.617507,
                lon:-58.368538
            },
            availability:{
                monday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                tuesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                wednesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                thursday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                friday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                saturday:{
                    "start_time":"00:00:00",
                    "end_time":"00:00:00"
                },
                sunday:{
                    "start_time":"09:00:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },{
            id:"d290f1ee-6c54-4b01-90e6-d701748f0851",
            name:"La Farola",
            business_name:"La Farola S.A.",
            address:{
                name:"Av. Paseo Colón 850",
                lat:-34.617591,
                lon:-58.368398
            },
            availability:{
                monday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                sunday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f1829",
            name:"La Birra Night",
            business_name:"La Birra",
            address:{
                name:"Av. Independencia 4317",
                lat:-34.617591,
                lon:-58.368561
            },
            availability:{
                monday:{
                    "start_time":"20:00:00",
                    "end_time":"23:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Burger Kid",
                    "price":280
                }
            ],
            delay_time:{
                min:40,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f0832",
            name:"San Carlos",
            business_name:"Pizzería San Carlos SRL",
            address:{
                name:"Av. Rivadavia 4480",
                lat:-34.617507,
                lon:-58.368538
            },
            availability:{
                monday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                tuesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                wednesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                thursday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                friday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                saturday:{
                    "start_time":"00:00:00",
                    "end_time":"00:00:00"
                },
                sunday:{
                    "start_time":"09:00:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },{
            id:"d290f1ee-6c54-4b01-90e6-d701748f0851",
            name:"La Farola",
            business_name:"La Farola S.A.",
            address:{
                name:"Av. Paseo Colón 850",
                lat:-34.617591,
                lon:-58.368398
            },
            availability:{
                monday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                sunday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f1829",
            name:"La Birra Night",
            business_name:"La Birra",
            address:{
                name:"Av. Independencia 4317",
                lat:-34.617591,
                lon:-58.368561
            },
            availability:{
                monday:{
                    "start_time":"20:00:00",
                    "end_time":"23:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Burger Kid",
                    "price":280
                }
            ],
            delay_time:{
                min:40,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f0832",
            name:"San Carlos",
            business_name:"Pizzería San Carlos SRL",
            address:{
                name:"Av. Rivadavia 4480",
                lat:-34.617507,
                lon:-58.368538
            },
            availability:{
                monday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                tuesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                wednesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                thursday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                friday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                saturday:{
                    "start_time":"00:00:00",
                    "end_time":"00:00:00"
                },
                sunday:{
                    "start_time":"09:00:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },{
            id:"d290f1ee-6c54-4b01-90e6-d701748f0851",
            name:"La Farola",
            business_name:"La Farola S.A.",
            address:{
                name:"Av. Paseo Colón 850",
                lat:-34.617591,
                lon:-58.368398
            },
            availability:{
                monday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                sunday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f1829",
            name:"La Birra Night",
            business_name:"La Birra",
            address:{
                name:"Av. Independencia 4317",
                lat:-34.617591,
                lon:-58.368561
            },
            availability:{
                monday:{
                    "start_time":"20:00:00",
                    "end_time":"23:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Burger Kid",
                    "price":280
                }
            ],
            delay_time:{
                min:40,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f0832",
            name:"San Carlos",
            business_name:"Pizzería San Carlos SRL",
            address:{
                name:"Av. Rivadavia 4480",
                lat:-34.617507,
                lon:-58.368538
            },
            availability:{
                monday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                tuesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                wednesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                thursday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                friday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                saturday:{
                    "start_time":"00:00:00",
                    "end_time":"00:00:00"
                },
                sunday:{
                    "start_time":"09:00:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },{
            id:"d290f1ee-6c54-4b01-90e6-d701748f0851",
            name:"La Farola",
            business_name:"La Farola S.A.",
            address:{
                name:"Av. Paseo Colón 850",
                lat:-34.617591,
                lon:-58.368398
            },
            availability:{
                monday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                sunday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f1829",
            name:"La Birra Night",
            business_name:"La Birra",
            address:{
                name:"Av. Independencia 4317",
                lat:-34.617591,
                lon:-58.368561
            },
            availability:{
                monday:{
                    "start_time":"20:00:00",
                    "end_time":"23:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Burger Kid",
                    "price":280
                }
            ],
            delay_time:{
                min:40,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f0832",
            name:"San Carlos",
            business_name:"Pizzería San Carlos SRL",
            address:{
                name:"Av. Rivadavia 4480",
                lat:-34.617507,
                lon:-58.368538
            },
            availability:{
                monday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                tuesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                wednesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                thursday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                friday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                saturday:{
                    "start_time":"00:00:00",
                    "end_time":"00:00:00"
                },
                sunday:{
                    "start_time":"09:00:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },{
            id:"d290f1ee-6c54-4b01-90e6-d701748f0851",
            name:"La Farola",
            business_name:"La Farola S.A.",
            address:{
                name:"Av. Paseo Colón 850",
                lat:-34.617591,
                lon:-58.368398
            },
            availability:{
                monday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                sunday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f1829",
            name:"La Birra Night",
            business_name:"La Birra",
            address:{
                name:"Av. Independencia 4317",
                lat:-34.617591,
                lon:-58.368561
            },
            availability:{
                monday:{
                    "start_time":"20:00:00",
                    "end_time":"23:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Burger Kid",
                    "price":280
                }
            ],
            delay_time:{
                min:40,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f0832",
            name:"San Carlos",
            business_name:"Pizzería San Carlos SRL",
            address:{
                name:"Av. Rivadavia 4480",
                lat:-34.617507,
                lon:-58.368538
            },
            availability:{
                monday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                tuesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                wednesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                thursday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                friday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                saturday:{
                    "start_time":"00:00:00",
                    "end_time":"00:00:00"
                },
                sunday:{
                    "start_time":"09:00:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },{
            id:"d290f1ee-6c54-4b01-90e6-d701748f0851",
            name:"La Farola",
            business_name:"La Farola S.A.",
            address:{
                name:"Av. Paseo Colón 850",
                lat:-34.617591,
                lon:-58.368398
            },
            availability:{
                monday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                sunday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f1829",
            name:"La Birra Night",
            business_name:"La Birra",
            address:{
                name:"Av. Independencia 4317",
                lat:-34.617591,
                lon:-58.368561
            },
            availability:{
                monday:{
                    "start_time":"20:00:00",
                    "end_time":"23:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Burger Kid",
                    "price":280
                }
            ],
            delay_time:{
                min:40,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f0832",
            name:"San Carlos",
            business_name:"Pizzería San Carlos SRL",
            address:{
                name:"Av. Rivadavia 4480",
                lat:-34.617507,
                lon:-58.368538
            },
            availability:{
                monday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                tuesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                wednesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                thursday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                friday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                saturday:{
                    "start_time":"00:00:00",
                    "end_time":"00:00:00"
                },
                sunday:{
                    "start_time":"09:00:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },{
            id:"d290f1ee-6c54-4b01-90e6-d701748f0851",
            name:"La Farola",
            business_name:"La Farola S.A.",
            address:{
                name:"Av. Paseo Colón 850",
                lat:-34.617591,
                lon:-58.368398
            },
            availability:{
                monday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                sunday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f1829",
            name:"La Birra Night",
            business_name:"La Birra",
            address:{
                name:"Av. Independencia 4317",
                lat:-34.617591,
                lon:-58.368561
            },
            availability:{
                monday:{
                    "start_time":"20:00:00",
                    "end_time":"23:30:00"
                },
                tuesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                wednesday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                thursday:{
                    "start_time":"19:30:00",
                    "end_time":"23:30:00"
                },
                friday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                },
                saturday:{
                    "start_time":"19:30:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Burger Kid",
                    "price":280
                }
            ],
            delay_time:{
                min:40,
                max:60
            }
        },
        {
            id:"d290f1ee-6c54-4b01-90e6-d701748f0832",
            name:"San Carlos",
            business_name:"Pizzería San Carlos SRL",
            address:{
                name:"Av. Rivadavia 4480",
                lat:-34.617507,
                lon:-58.368538
            },
            availability:{
                monday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                tuesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                wednesday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                thursday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                friday:{
                    "start_time":"09:00:00",
                    "end_time":"00:00:00"
                },
                saturday:{
                    "start_time":"00:00:00",
                    "end_time":"00:00:00"
                },
                sunday:{
                    "start_time":"09:00:00",
                    "end_time":"00:30:00"
                }
            },
            menu:[
                {
                    name:"Matambre a la pizza",
                    "price":250
                }
            ],
            delay_time:{
                min:null,
                max:60
            }
        }
    ]
};